add_subdirectory(test_utils)

add_subdirectory(HelloWindow)
add_subdirectory(HelloTriangle)
add_subdirectory(Uniforms)
add_subdirectory(ParallelPass)
add_subdirectory(MultiWindow)

# texturing
add_subdirectory(Texturing)
add_subdirectory(DownloadImages)
add_subdirectory(TextureArray)
add_subdirectory(LayeredTexture)
add_subdirectory(TextureAtlas)


# hard examples
add_subdirectory(Cube)
#add_subdirectory(OIT)